name: Laboratorio Final

on:
  push:
  workflow_dispatch:

jobs:
  SAST:
    name: Static Application Security Testing (SAST) con SonarCloud
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          echo "Instalando dependencias del proyecto..."
          npm install

      - name: Analisis con SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=laboratorio-final-glemos
            -Dsonar.organization=glemosas
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Validar vulnerabilidades
        run: |
          echo "Analizando vulnerabilidades"
          response=$(curl -s "https://sonarcloud.io/api/issues/search?componentKeys=laboratorio-final-glemos&types=VULNERABILITY&severities=BLOCKER,CRITICAL,MAJOR")
          echo "Respuesta de SonarCloud: $response"
          vulnerabilities=$(echo "$response" | jq -r '.total // 0')
          if [[ ! "$vulnerabilities" =~ ^[0-9]+$ ]]; then
            echo "La variable vulnerabilities no contiene un número válido. Valor recibido: '$vulnerabilities'"
            exit 1
          fi
          echo "Valor de variable: $vulnerabilities"

          # Verificar si se encontraron vulnerabilidades
          if [ "$vulnerabilities" -gt 0 ]; then
            echo "Se encontraron $vulnerabilities vulnerabilidades críticas, altas o medias. Deteniendo pipeline."
          # Descomenta para detener el pipeline
          # exit 1
          else
            echo "No se encontraron vulnerabilidades críticas, altas o medias."
          fi
