name: Laboratorio Final

on:
  push:
  workflow_dispatch:

jobs:
  SAST:
    name: Static Application Security Testing (SAST) con SonarCloud
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          echo "Instalando dependencias del proyecto..."
          npm install

      - name: Analisis con SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=GLemos-AS_laboratorio-final-glemos2
            -Dsonar.organization=glemosas
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Validar vulnerabilidades
        run: |
          echo "Analizando vulnerabilidades"
          
          # Guardamos componentKeys en una variable
          COMPONENT_KEY="GLemos-AS_laboratorio-final-glemos2"
          
          # Realizamos la consulta para obtener las vulnerabilidades CRITICAL
          response_critical=$(curl -s "https://sonarcloud.io/api/issues/search?componentKeys=$COMPONENT_KEY&types=VULNERABILITY&severities=CRITICAL")
          critical_vulnerabilities=$(echo "$response_critical" | jq -r '.total // 0')

          # Realizamos la consulta para obtener las vulnerabilidades HIGH (altas)
          response_high=$(curl -s "https://sonarcloud.io/api/issues/search?componentKeys=$COMPONENT_KEY&types=VULNERABILITY&severities=HIGH")
          high_vulnerabilities=$(echo "$response_high" | jq -r '.total // 0')

          # Realizamos la consulta para obtener las vulnerabilidades MAJOR (medias)
          response_major=$(curl -s "https://sonarcloud.io/api/issues/search?componentKeys=$COMPONENT_KEY&types=VULNERABILITY&severities=MAJOR")
          major_vulnerabilities=$(echo "$response_major" | jq -r '.total // 0')

          # Verificar si las variables contienen números válidos
          if [[ ! "$critical_vulnerabilities" =~ ^[0-9]+$ ]] || [[ ! "$high_vulnerabilities" =~ ^[0-9]+$ ]] || [[ ! "$major_vulnerabilities" =~ ^[0-9]+$ ]]; then
            echo "Al menos una de las variables no contiene un número válido. Valor crítico: '$critical_vulnerabilities', Valor alto: '$high_vulnerabilities', Valor medio: '$major_vulnerabilities'"
            exit 1
          fi

          # Mostrar el número de vulnerabilidades de cada tipo
          echo "Vulnerabilidades críticas: $critical_vulnerabilities"
          echo "Vulnerabilidades altas: $high_vulnerabilities"
          echo "Vulnerabilidades medias: $major_vulnerabilities"

          # Verificar si se encontraron vulnerabilidades de cualquier tipo
          if [ "$critical_vulnerabilities" -gt 0 ] || [ "$high_vulnerabilities" -gt 0 ] || [ "$major_vulnerabilities" -gt 0 ]; then
            echo "Se encontraron vulnerabilidades críticas, altas o medias. Deteniendo pipeline."

            # Detener el pipeline si se encuentran vulnerabilidades de cualquier tipo
            # exit 1
          else
            echo "No se encontraron vulnerabilidades críticas, altas o medias."
          fi
  SCA:
    needs: SAST
    name: Software Composition Analysis (SCA)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Instalar Java
      #   run: |
      #     sudo apt update
      #     sudo apt install -y openjdk-11-jdk
      #     java -version

      - name: OWASP Dependency Check
        run: |
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.1/dependency-check-11.1.1-release.zip -o dependency-check.zip
          unzip dependency-check.zip -d $HOME/dependency-check

      - name: Debug Dependency Check
        run: ls -l $HOME/dependency-check/dependency-check/bin

      - name: Make dependency-check.sh executable
        run: chmod +x $HOME/dependency-check/dependency-check/bin/dependency-check.sh

      - name: Run Dependency Check
        run: |
          $HOME/dependency-check/dependency-check/bin/dependency-check.sh \
            --project "GLemos-AS_laboratorio-final-glemos2" \
            --scan . \
            --out ./dependency-check-report \
            --format "ALL"
      
      - name: Contar vulnerabilidades por severidad
        run: |
          echo "Analizando el reporte de dependencias para contar vulnerabilidades..."

          # Se utiliza el reporte generado para contar las vulnerabilidades por severidad
          critical_count=$(grep -i 'Critical' ./dependency-check-report/*.html | wc -l)
          high_count=$(grep -i 'High' ./dependency-check-report/*.html | wc -l)
          medium_count=$(grep -i 'Medium' ./dependency-check-report/*.html | wc -l)

          echo "Vulnerabilidades críticas: $critical_count"
          echo "Vulnerabilidades altas: $high_count"
          echo "Vulnerabilidades medias: $medium_count"

          # Verificar si se deben fallar las vulnerabilidades según los umbrales
          if [ "$critical_count" -gt 0 ]; then
            echo "Se encontraron vulnerabilidades críticas. Deteniendo pipeline."
            exit 1
          elif [ "$high_count" -gt 0 ]; then
            echo "Se encontraron vulnerabilidades altas. Deteniendo pipeline."
            exit 1
          elif [ "$medium_count" -gt 0 ]; then
            echo "Se encontraron vulnerabilidades medias. Deteniendo pipeline."
            exit 1
          else
            echo "No se encontraron vulnerabilidades críticas, altas o medias."
          fi
      
      - name: Subir reporte
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ./dependency-check-report/*.html

